apiVersion: v1
kind: ReplicationController
metadata:
  name: myinginx-rc
spec:
  replicas: 6
  selector:
    app: mynginx
  template:
    metadata:
      
      labels:
        app: mynginx
    spec:
      containers:
        - name: mycontainer
          image: nginx
          ports:
            - containerPort: 80
